### ISSUE TITLE
use "parfile" as prefix for the "predictions" file

### ISSUE THREAD

**Issue by timflutre** [alegarra/gs3#3]
This would require changing line 270 from:

```
open(unit=12,file='predictions',status='replace')
```

to:

```
open(unit=12,file=trim(parfile)//'_predictions',status='replace')
```

Otherwise, when doing cross validations, each fold can't be run in the same directory.

**Comment by alegarra** [comment]
Sure, you want to do it yourself? no problem

**Comment by timflutre** [comment]
Ok, I'll try by first forking the repo.

**Comment by timflutre** [comment]
I don't have the "ifort" compiler. So I tried with "gfortran" (replacing in `compile.sh`), but it returns an error:

```
gfortran: error: unrecognized command line option ‘-h’
```

which, I think, come from the following command:

```
gfortran -c -O3 -heap-arrays gs3.f90
```

When I disable this flag, the compilation succeeds. But is it ok? I couldn't (quickly) find any information about  `-heap-arrays` anywhere on the internet.

**Comment by timflutre** [comment]
I just made a pull request. You can merge it easily if it's ok for you.

**Comment by timflutre** [comment]
I closed the pull request because it doesn't solve the problem, yet.

**Comment by timflutre** [comment]
I opened a new pull request, now it should be fine, sorry!

You can merge it easily if it's ok for you.

**Comment by timflutre** [comment]
Great, thanks!
