### ISSUE TITLE
error in the manual about weights?

### ISSUE THREAD

**Issue by timflutre** [alegarra/gs3#7]
On page 6, the manual says that:

    y_i | ... ~ N(hat{y_i}, sigma^2_e / w_i)

From this formula, we see that the larger the weight (`w_i`), the smaller the error variance specific of observation i (`sigma_e^2 /w_i`).

I am using BLUPs as `y_i`, and I also want to use their variances. On my data sets, when the BLUP variance is larger than others, it corresponds to the fact that the given genotype has more missing data than others.

If one follows the formula in the manual, I should use `w_i = 1 / var(BLUP_i)`. However, the results look really bad, compare to using `w_i = var(BLUP_i)`.

Is there an error in the manual?

**Comment by alegarra** [comment]
Timothee, what do you mean *exactly* as var(BLUP_i) ? It depends if it is
var(u\hat) or var(u\hat | y) .

Andres

**Comment by timflutre** [comment]
`var(u\hat | y)`

Details: I am using the `lmer` function from the `lme4` R package to fit the following linear mixed model via ReML:

    y = X beta + Z u + e

where `y` corresponds to phenotypic values obtained on a set of genotypes modeled as the random effects `u`. (Depending on the data sets, the genotypes were phenotyped in several blocks, multiple years, etc, and there often are missing data.)

I then use the `ranef` function from `lme4`, which returns the conditional modes of `u` as well as the corresponding variances. See equations 55 et 56 on [page 28 of the lme4 vignette](https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf#page=28).

**Comment by alegarra** [comment]
What horrible notation instead of using classical Hendersonian notation.

 Frequentist Var(u\hat) is Var(u\hat) = Var(u) - Var(u\hat | y)

Bayesian Var(u\hat | y)  are called PEV's (prediction error variances). The
smaller the PEV the more accurate the variance. So, the weight should be
1/PEV or 1/variance(BLUP|y). If this is what you're using, then it should
be fine.

The problem might be on ignoring covariances across BLUP's :-(
Using BLUP's as inputs for GS is a bad idea unless they are very accurate.

**Comment by timflutre** [comment]
Thank you for your quick answer. But so I am doing something very wrong...

When I use `weights = 1/variance(BLUP|y)`, I obtain a proportion of variance explained by the SNPs which is extremely low. (By "proportion of variance explained by the SNPs", I mean `2varapqpi / ( 2varapqpi + vare )`.) When I am using `weights = variance(BLUP|y)`, the PVE_SNPs is extremely high, that's why I thought it was the proper way of using the weights.

But if I understand well your advice, one should never use BLUPs as inputs for GS. So, in the case where one wants to keep a two-stage analysis, you are recommending to use BLUEs as inputs for GS, with `weights = 1/variance(BLUEs)`, is that right?

**Comment by alegarra** [comment]
This is getting complicated to put on this github thing. Should we take by
the phone or skype? Tomorrow afternoon or next week.

**Comment by timflutre** [comment]
Ok for tomorrow after noon, thanks a lot! I will call you at 2pm on the telephone number indicated [here](http://annuaire.inra.fr/afficherPersonne.action?req=HvGqk%2FQeeO6wE0aAfjrIIo3pSYeaMhZ8lpk3UuX%2B9FY%3D&personneRecherche.nom=legarra&personneRecherche.approchee=false&personneRecherche.prenom=andr%C3%A9s) in the Inra directory.
